# Requirements for Binder
# i.e. what is needed to run the example notebooks
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip:
    - movement
    - networkx.   # not included with movement core, only comes with movement[napari]
