# Run weekly checks to ensure movement can be installed from conda-forge
# alongside napari and a Qt backend without conflicts.
name: conda install check

on:
    schedule:
        # Weekly cron job at 12:00 AM UTC on Mondays.
        - cron: '0 0 * * 1'
    workflow_dispatch:

jobs:
  conda_install_check:
    name: Conda install check (${{ matrix.os }} py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]

    defaults:
      run:
        shell: bash -l {0}  # Required for conda activation

    steps:
      - uses: actions/checkout@v6
      # pinning to a specific sha1 is recommended by this action's docs
      - uses: conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f # v3.2.0
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          channels: conda-forge
          conda-remove-defaults: true
          activate-environment: "movement-test"
      - name: Check conda installation
        run: |
          conda install -c conda-forge movement napari pyqt
          movement info
